language: shell

addons:
  chrome: stable
  
before_script:
  # Download and unzip the zola executable
  # Replace the version numbers in the URL by the version you want to use
  - curl -s -L https://github.com/getzola/zola/releases/download/v0.11.0/zola-v0.11.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

script:
  - zola serve > /dev/null 2>&1 &
  - export ZOLA_PID=$!
  - google-chrome-stable --headless --disable-gpu --print-to-pdf-no-header --print-to-pdf=static/alexlauni_resume.pdf http://127.0.0.1:1111/cv
  - kill $ZOLA_PID
  - zola build

deploy:
  provider: pages
  cleanup: false
  local_dir: public
  token: $GH_TOKEN
  on:
    branch: main 
