name: GitHub Pages CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Zola
        run: sudo snap install --edge zola
      - name: Build PDF CV
        run: |
          zola serve &
          export ZOLA_PID=$!
          sleep 5
          curl localhost:1111
          curl localhost:1111/cv
          google-chrome --headless --run-all-compositor-stages-before-draw --print-to-pdf-no-header --print-to-pdf=static/alexlauni-resume.pdf http://localhost:1111/cv
          kill $ZOLA_PID
          cat static/alexlauni-resume.pdf
          ls static
          
  build_and_deploy:
    name: Build site with Zola and deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@master
    - name: Build PDF CV
      run: |
        sudo snap install --edge zola
        zola serve 2>&1 &
        export ZOLA_PID=$!
        google-chrome --headless --run-all-compositor-stages-before-draw --print-to-pdf-no-header --print-to-pdf=static/alexlauni-resume.pdf http://127.0.0.1:1111/cv/
        kill $ZOLA_PID
    - name: Zola Deploy Action by @shalzz
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.TOKEN }}
