name: GitHub Pages CI
on: [push]

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Zola
        run: sudo snap install --edge zola
      - name: Verify build/links
        run: zola check
